#include "pokergame.h"

int main(int argc, char **argv){
  int i=0;
  int j=0;
  int setloop=1;     /*a set is a completely new redraw from a full deck. keep playing new sets until only one player has all the money*/
  int roundloop=1;   /*each set is made up of 2 rounds. players left after the 2nd round reveal their cards*/
  int numbankruptplayers=0;
  int numfolded =0;

  Card ** tmpCard = (Card **)malloc(sizeof(Card *));
  Deck * playingDeck = (Deck *)malloc(sizeof(Deck));
  Player ** players = (Player **)malloc(sizeof(Player*)*NUMPLAYERS);
  int sims = atoi(argv[1]);//runs 32*sims simulations

  int abet=0;          /*temp var to hold a bet*/
  int pool=0;          /*total money bet by players during a set, i.e. the amount that goes to the winner*/
  int maxcumulbet=0;   /*the cumulative max amount in the pool by any one player. this is the minimum cumulative bet in round 2 for all other players.*/

  //variables to hold logic to act on. Generated by Monte Carlo advisor
  int *maxdiscards = (int*)malloc(sizeof(int)*HAND_SIZE);  /*index of the cards in players[i]->hand that Monte Carlo advisor thinks player should discard*/
  int *maxthrown = (int*)malloc(sizeof(int));              /*number of cards Monte Carlo advisor thinks the player should discard*/
  int *maxvalue = (int*)malloc(sizeof(int));               /*highest expected value out of all 32 discard options available. Used by AI to determine a bet amount. */
  int adiscard=0;
 
  int maxplayer=0;         /*holds the index corresponding to the player with the highest value hand in Player ** players */
  int maxplayervalue=0;    /*holds the highest value hand found while iterating over all the players*/

  char str[]="0";

  srand(time(NULL));
  printf("\n\n\n\n========[Welcome to Five Card Monte Carlo Poker]========\n\n");
  printf("Rules:\n(A) 2 rounds of betting per set. Bets go into the 'pool'.\n(B) Every player must call the highest bet after round 1 in order to remain in the game.\n(C) In each round, every player may discard and draw up to 5 cards from the deck.\n(D) A player may also choose to fold at any time, but forfeits any bets they already made.\n(E) Player with the highest set of cards at the end of 2 rounds wins all the money in the pool.\n(F)The game continues in sets of 2 rounds until all players except one is bankrupt.\n");
  
  //initialize players
  for(i=0;i<NUMPLAYERS;i++){
    players[i]= (Player *)malloc(sizeof(Player));
    player_init(players[i]);
    sprintf(str,"%d",i);
    strcat(players[i]->name,"Player");
    strcat(players[i]->name,str);
  }


  printf("\nEnter a name for yourself (No spaces, up to 20 characters):\n");
  scanf("%s",players[0]->name);

  //set up the deck of cards
  deck_init(playingDeck);
  deck_fill(playingDeck);
  shuffle(playingDeck,2000);

  //start game loop
  while(setloop!=0){

    //distribute cards to players
    for(i=0;i<HAND_SIZE;i++){
      for(j=0;j<NUMPLAYERS;j++){
	if(players[j]->money>0){
	  dequeue_card(playingDeck,tmpCard);
	  add_card(players[j]->hand,*tmpCard);
	}
      }
    }
    
    //sort all player hands
    for(i=0;i<NUMPLAYERS;i++){
      if(players[i]->money>0)
	hand_sort(players[i]->hand);
    }

    while(roundloop!=3){
      printf("\n====================[Set: %d Round: %d]====================\n\n",setloop,roundloop);
      printf("The pool has $%d\n",pool);
      for(i=0;i<NUMPLAYERS;i++){
	if(players[i]->fold==FOLDED && players[i]->money==0 && players[i]->bet==0)
	  printf("%s is bankrupt\n",players[i]->name);
	else if(players[i]->fold==FOLDED)
	  printf("%s folded and has $%d in the pool.\n",players[i]->name,players[i]->bet);
	else
	  printf("%s has $%d left and $%d in the pool.\n",players[i]->name,players[i]->money, players[i]->bet);
      }
      putchar('\n');

      for(i=0;i<NUMPLAYERS;i++){
	//stop the round if all other players folded and immediate award money to remaining player
	if(numfolded==NUMPLAYERS-1)
	  break;

	//only players that didnt fold and have money can play in the round
	if(players[i]->fold!=FOLDED && players[i]->money>0){

	  //set up variables to retrieve info from Monte Carlo sim to help make decisions
	  for(j=0;j<HAND_SIZE;j++){
	    maxdiscards[j]=-1;
	  }
	  *maxthrown=0;
	  *maxvalue=0;
	  
	  //run Monte Carlo simulation
	  mc(players[i]->hand,maxdiscards,maxthrown,maxvalue,sims);

	  //game interface to present to human player 
	  if(i==HUMANPLAYER){
	    printf("Your hand is:\n");
	    hand_toString_ordered(players[i]->hand);
	    printf("You must add at least $%d to the pool to continue playing.\n",maxcumulbet-players[i]->bet);
	    printf("Your chips: $%d\n",players[i]->money);
	    printf("How much do you want to add to the pool? (Enter -1 to fold)");
	    abet = get_incremental_bet(players[i],maxcumulbet);
	    if(players[i]->fold==FOLDED){
	      numfolded +=1;
	      printf("You folded.\n");
	    }
	    else{
	      if((abet+players[i]->bet)>maxcumulbet)
		maxcumulbet = abet+players[i]->bet;
	      players[i]->bet += abet;
	      players[i]->money -= abet;
	      pool += abet;

	      if(*maxthrown==0)   
		printf("\nThe advisor says: I think you should keep all your cards.\n");
	      else{
		if(*maxthrown==1) 
		  printf("\nThe advisor says: I think you should discard %d card:\n",*maxthrown);
		else              
		  printf("\nThe advisor says: I think you should discard %d cards:\n",*maxthrown);
		for(j=0;j<*maxthrown;j++){
		  printf("[%d] ",maxdiscards[j]+1);
		  card_toString(players[i]->hand->cards[maxdiscards[j]]);
		}
	      }
	      
	      //Request human input - decide which cards to discard
	      *maxthrown=0;
	      for(j=0;j<HAND_SIZE;j++){
		printf("Enter the number[1-5] of ONE card you wish to discard, or 0 if done discarding, or 6 to fold:");
		scanf("%d",&adiscard);
		
		if(adiscard==0)
		  break;
		
		if(adiscard==6){
		  printf("You folded.\n");
		  players[i]->fold=FOLDED;
		  numfolded +=1;
		  break;
		}

		//check validity of human input regarding cards they want to discard and save the valid input
		if(check_input(adiscard,maxthrown,maxdiscards)!=0){
		  j--;
		  adiscard=-1;
		}else{
		  maxdiscards[*maxthrown]=adiscard-1;
		  (*maxthrown)++;
		  printf("     Discarding: ");
		  card_toString(players[i]->hand->cards[adiscard-1]);
		  putchar('\n');
		}
	      }
	      if(players[i]->fold!=FOLDED)
		printf("You decided to discard %d cards.\n",*maxthrown);
	    }
	  }//end interface for human player
	  
	  //game interface for computer players
	  else{
	    abet = get_max_incremental_bet(players[i],*maxvalue,maxcumulbet);
	    if(players[i]->fold==FOLDED){
	      numfolded +=1;
	      printf("%s folded.\n",players[i]->name);
	    }
	    else{
	      if((abet+players[i]->bet)>maxcumulbet)
		maxcumulbet = abet+players[i]->bet;
	      printf("%s decided to add $%d to the pool.\n",players[i]->name,abet);
	      players[i]->bet += abet;
	      players[i]->money -= abet;
	      pool += abet;
	      printf("%s decided to discard %d cards.\n",players[i]->name,*maxthrown);
	      sleep(1);
	    }
	  }

	  //act on Monte Carlo advisor's advice (or human input)
	  if(players[i]->fold!=FOLDED){
	    for(j=0;j<*maxthrown;j++){
	      dequeue_card(playingDeck,tmpCard);
	      replace_card(players[i]->hand,maxdiscards[j],*tmpCard);
	    }
	    hand_sort(players[i]->hand);
	  }
	  
	}//end if(player[i]->fold=folded)
      }//end for loop that is run for each players turn      
      roundloop++;
    }//end round loop
    
    //find the player with the highest card and award them the pool, when there is more than one player remaining at the end of two rounds
    if(numfolded!=NUMPLAYERS-1){
      printf("\nTime for the showdown!\n");
      sleep(1);
      for(i=0;i<NUMPLAYERS;i++){
	if(players[i]->fold!=FOLDED && players[i]->money>=0 && players[i]->bet>0){
	  hand_value(players[i]->hand);
	  printf("\n%s has: %s\n",players[i]->name,players[i]->hand->class);
	  sleep(1);
	  hand_toString(players[i]->hand);
	  if(players[i]->hand->value>maxplayervalue){
	    maxplayervalue = players[i]->hand->value;
	    maxplayer = i;
	  }
	}
      }
      if(maxplayer==HUMANPLAYER){
	printf("\nYou won the showdown with a %s!!!\n",players[maxplayer]->hand->class);
	printf("\nYou won $%d!!!\n",pool);
      }else{
	printf("\n%s wins the showdown with a %s!!!\n",players[maxplayer]->name,players[maxplayer]->hand->class);
	printf("\n%s won $%d!!!\n",players[maxplayer]->name,pool);
      }
     
      players[maxplayer]->money += pool;

    }
    //award money to the only remaining player when everyone folded
    else{
      for(i=0;i<NUMPLAYERS;i++){
	if(players[i]->fold!=FOLDED){
	  printf("Everyone folded except for %s\n",players[i]->name);
	  printf("%s won $%d!!!\n",players[i]->name,pool);
	  players[i]->money += pool;
	}
      }
    }

    //look for newly bankrupt players
    for(i=0;i<NUMPLAYERS;i++){
      if(players[i]->money==0 && players[i]->bet>0){
	printf("%s is bankrupt and out of the game.\n",players[i]->name);
	numbankruptplayers++;
	players[i]->fold=FOLDED;
      }
    }

    roundloop=1;
    setloop++;

    //end the game if only one remaining player has money
    if(numbankruptplayers==NUMPLAYERS-1){
      printf("Game over. %s wins with $%d in winnings. All other players are bankrupt.\n",players[maxplayer]->name,players[maxplayer]->money);
      setloop=0;
    }

    /*reset the deck*/
    enqueue_deck(playingDeck);
    shuffle(playingDeck,1500);
    
    /*reset the hands of all players*/
    for(i=0;i<NUMPLAYERS;i++){
      if(players[i]->money!=0)//only reset players fold status if they have money. keep them folded if they are bankrupt
	players[i]->fold=0;
      players[i]->bet=0;
      player_reset_hand(players[i]);
    }

    /*reset values of the set loop*/
    maxplayer=0;
    maxplayervalue=0;
    pool=0;
    maxcumulbet=0;
    numfolded=0;

  }//end set loop
    
  /*clean up*/
  deck_destroy(playingDeck);
  for(i=0;i<NUMPLAYERS;i++){
    player_destroy(players[i]);
  }

  return 0;
}

/*validate player input regarding which cards they want to discard. reject invalid numeric input*/
int check_input(int adiscard, int*maxthrown, int*maxdiscards){
  int k=0;
  if(adiscard>6 || adiscard <0){
    printf("You did not enter a valid option. Please try again\n");
    return 1;
  }
  for(k=0;k<*maxthrown;k++){
    if((adiscard-1)==maxdiscards[k]){
      printf("     You already discarded that card.\n");
      return 2;
    }
  }
  return 0;
}

/*calculate the max amount the computer is willing to bet, based on expected value*/
int get_max_incremental_bet(Player * player, int expectedvalue, int maxcumulbet){
  double maxbet = (INITIALMONEY)*((float)expectedvalue/CARDVALUES);
  int maxbeti = maxbet;
  int bet = maxbeti-player->bet;
  //printf("\ncomputer: maxbet:%f, bet:%d, expval:%d, maxcumulbet:%d, playerbet:%d, playermoney:%d\n",maxbet,bet,expectedvalue,maxcumulbet,player->bet,player->money);
  //bet only if the incremental amount the computer is willing to bet is greater than what is needed to call
  if(bet>=maxcumulbet-player->bet){
    //all in if the bet amount is greater than amount the player has or if money is low and the computer has a pair
    if(bet>player->money || (player->money<30 && expectedvalue>13*2))
      return player->money;
    return bet;
  }else if(player->bet==maxcumulbet){//if the incremental bet isn't higher than what is needed to call, but the player is the highest bet already, stay
    return 0;
  }else{//otherwise fold
    player->fold=FOLDED;
    return -1;
  }
}

//get a valid amount from the human player to add to their bet
int get_incremental_bet(Player * player, int currentbet){
  int abet=0;
  scanf("%d",&abet);
  if(abet<0){
    player->fold=FOLDED;
    return -1;
  }
  if(abet<(currentbet-player->bet)){
    printf("You must add at least %d to the pool. Please try again. (Enter -1 to fold).",currentbet-player->bet);
    return get_incremental_bet(player,currentbet);
  }
  if(abet>player->money){
    printf("You only have $%d. Please try again. (Enter -1 to fold).",player->money);
    return get_incremental_bet(player,currentbet);
  }
  return abet;
}
